import React from 'react';
import { Link } from 'react-router-dom';
import showroom from './background1.jpg';
import { getSahibindenUrl } from '../utils/externalLinks';
import './Home.css';
const services = [ ['fa-magnifying-glass','Detaylı ekspertiz','Bağımsız ekspertiz merkezlerinde inceleme ve açık raporlama.'], ['fa-file-contract','Güvenli devir','Noter ve ruhsat işlemlerinde baştan sona destek.'], ['fa-wallet','Nakit teklif','Aracınız için hızlı ve şeffaf değerlendirme.'], ['fa-location-dot','Türkiye genelinde','Yerinde araç alım ve satım hizmeti.'] ];
export default function Home() { return <>
<section className="home-hero"><div className="container hero-grid"><p className="eyebrow hero-eyebrow">AYDINLAR OTOMOTİV · ERZURUM</p><h1>Yeni yolculuğunuz<br /><em>burada başlar.</em></h1><figure className="hero-photo"><img src={showroom} alt="Galeride sergilenen siyah araçlar" fetchPriority="high" /><figcaption><span>AYDINLAR SEÇKİSİ</span><span>Yeni bir başlangıca hazır. ↗</span></figcaption></figure><p className="hero-description">İkinci el araç alım ve satımında doğru seçim, şeffaf süreç ve güvenle atılan yeni bir adım.</p><div className="button-row"><a className="button button-red" href={getSahibindenUrl()}>Araçları incele <span aria-hidden="true">↗</span></a><a className="button button-outline" href="https://wa.me/905333731113" target="_blank" rel="noopener noreferrer">WhatsApp’tan ulaş</a></div><div className="hero-note"><span className="small-line" /> Sizin için doğru araç. Her adımda yanınızda.</div></div></section>
<section className="services-section"><div className="container"><div className="section-heading"><p className="eyebrow">HER ADIMDA GÜVEN</p><h2>İyi bir araçtan<br />daha fazlası.</h2></div><div className="services-grid">{services.map(([icon,title,text])=><article key={title} className="service"><i aria-hidden="true" className={'fa-solid '+icon}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="home-story container"><div><p className="eyebrow">BİZİ TANIYIN</p><h2>Bir araç alışverişi.<br />Uzun soluklu bir güven.</h2></div><div><p>Erzurum’da Aydınlar Otomotiv olarak, ihtiyaçlarınıza uygun aracı bulmanız için yanınızdayız. Açık iletişimi ve şeffaf bir alışveriş deneyimini önemsiyoruz.</p><Link className="text-link" to="/hakkimizda">Hikayemizi keşfedin <span aria-hidden="true">↗</span></Link></div></section>
</>; }
